apiVersion: v2
name: lightbridge
description: The Lightbridge VNA Application Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

# These are the "Off the Shelf" building blocks we are downloading
dependencies:
  - name: minio
    version: 5.0.14
    repository: https://charts.min.io/
  - name: keycloak
    version: 18.4.3
    repository: https://charts.bitnami.com/bitnami