apiVersion: v2
name: lightbridge
description: The Lightbridge VNA Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # 1. MinIO (Object Storage)
  - name: minio
    version: 5.0.14
    repository: https://charts.min.io/

  # 2. Keycloak (Identity Provider)
  - name: keycloak
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
    
  # NOTE: Orthanc, OHIF, and the Postgres Cluster definitions are 
  # NOT listed here because they are defined locally in /templates.