apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ohif
  labels:
    app: ohif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohif
  template:
    metadata:
      labels:
        app: ohif
    spec:
      containers:
        - name: ohif
          image: ohif/viewer:v3.8.0
          ports:
            - containerPort: 80
          volumeMounts:
            # Overwrite the default config.js with our custom version
            - name: ohif-config-volume
              mountPath: /usr/share/nginx/html/app-config.js
              subPath: app-config.js
      volumes:
        - name: ohif-config-volume
          configMap:
            name: ohif-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ohif
spec:
  selector:
    app: ohif
  ports:
    - port: 80
      targetPort: 80